name: Paperturn Website
on:
  push:
    branches: [ main ]

env:
  DEPLOYMENT_ROLE: arn:aws:iam::619075404012:role/GitHubDeployRole
  APPLICATION_NAME: PaperturnWebApplication
  DEPLOYMENT_GROUP: PaperturnWebDeploymentGroup
  ARTIFACT_BUCKET: dev-paperturninfrawebsit-codedeploycodedeploydepl-131acrtr827ji

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
          tools: composer:v2
      

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: List files
        run: |
          ls -ltra
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r vendor.zip vendor      

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: composer-dependencies
          path: |
            vendor.zip

  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    strategy:
      matrix:
        appname: ['PaperturnWebApplication']
        deploy-group: ['PaperturnWebDeploymentGroup']
        s3-bucket: ['dev-paperturninfrawebsit-codedeploycodedeploydepl-131acrtr827ji']
        s3-filename: ['staging-aws-codedeploy-${{ github.sha }}']

    permissions:
      actions: write
      contents: read
      id-token: write 
    steps:
      - uses: actions/checkout@v3
      
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: composer-dependencies

      - uses: montudor/action-zip@v1
        with:
          args: unzip -qq vendor.zip -d vendor
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::619075404012:role/GitHubDeployRole
          role-session-name: GithubActions
          aws-region: eu-west-1


      # Deploy push to AWS S3
      - name: List files
        run: |
          ls -ltra

      # Deploy push to AWS S3
      - name: AWS Deploy push
        run: |
          aws deploy push \
          --application-name ${{ matrix.appname }} \
          --description "This is a revision for the ${{ matrix.appname }}-${{ github.sha }}" \
          --ignore-hidden-files \
          --s3-location s3://${{ matrix.s3-bucket }}/${{ matrix.s3-filename }}.zip \
          --source .

      # Create deployment to CodeDeploy
      - name: AWS Create Deployment
        run: |
          aws deploy create-deployment \
           --application-name ${{ matrix.appname }} \
           --deployment-config-name CodeDeployDefault.OneAtATime \
           --deployment-group-name ${{ matrix.deploy-group }} \
           --file-exists-behavior OVERWRITE \
           --s3-location bucket=${{ matrix.s3-bucket }},key=${{ matrix.s3-filename }}.zip,bundleType=zip \
