name: Paperturn Website
on:
  push:
    branches: [ main ]

env:
  DEPLOYMENT_ROLE: arn:aws:iam::619075404012:role/GitHubDeployRole
  APPLICATION_NAME: PaperturnWebApplication

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
          tools: composer:v2
            
      - name: Print PHP version
        run: echo ${{ steps.setup-php.outputs.php-version }}      

      - name: Install dependencies
        run: composer install --prefer-dist

  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    permissions:
      actions: write
      contents: read
      id-token: write 
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: $DEPLOYMENT_ROLE
          role-session-name: GithubActions
          aws-region: eu-west-1

      - name: Test creds
        run: aws sts get-caller-identity

      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment --application-name $APPLICATION_NAME