name: Paperturn Website
on:
  push:
    branches: [ main ]


jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
          tools: composer:v2
      

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: List files
        run: |
          ls -ltra
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r vendor.zip vendor      

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: composer-dependencies
          path: |
            vendor.zip

  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    env:
      DEPLOYMENT_ROLE: arn:aws:iam::619075404012:role/GitHubDeployRole
      APP_NAME: PaperturnWebApplication
      DEPLOYMENT_GROUP: PaperturnWebDeploymentGroup
      ARTIFACT_BUCKET: dev-paperturninfrawebsit-codedeploycodedeploydepl-131acrtr827ji
      ARTIFACT_KEY: 'staging-aws-codedeploy-${{ github.sha }}'

    permissions:
      actions: write
      contents: read
      id-token: write 
    steps:
      - uses: actions/checkout@v3
      
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: composer-dependencies

      - uses: montudor/action-zip@v1
        with:
          args: unzip -qq vendor.zip -d .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::619075404012:role/GitHubDeployRole
          role-session-name: GithubActions
          aws-region: eu-west-1


      # Deploy push to AWS S3
      - name: List files
        run: |
          ls -ltra

      # Deploy push to AWS S3
      - name: AWS Deploy push
        run: |
          aws deploy push \
          --application-name $APP_NAME \
          --description "This is a revision for the $APP_NAME-${{ github.sha }}" \
          --ignore-hidden-files \
          --s3-location s3://$ARTIFACT_BUCKET/$ARTIFACT_KEY.zip \
          --source .

      # Create deployment to CodeDeploy
      - name: AWS Create Deployment
        run: |
          aws deploy create-deployment \
           --application-name $APP_NAME \
           --deployment-config-name CodeDeployDefault.OneAtATime \
           --deployment-group-name $DEPLOYMENT_GROUP \
           --file-exists-behavior OVERWRITE \
           --s3-location bucket=$ARTIFACT_BUCKET,key=$ARTIFACT_KEY.zip,bundleType=zip \
